# Generated by Django 4.2.7 on 2025-12-13 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('play_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='songs',
            old_name='duration',
            new_name='albom',
        ),
    ]
